FROM arm32v7/python:3.10-bullseye

RUN apt-get update && apt-get install -y \
    vim \
    cmake \
    git

RUN pip install --no-cache-dir \
    azure-iot-device \
    azure.iot.hub \
    azure-cosmos \
    tzupdate
    
WORKDIR /app

COPY . .

ENTRYPOINT ["bash", "init.sh"]